FROM nvcr.io/nvidia/pytorch:23.05-py3

COPY ./docker/requirements-app.txt /usr/src/docker/requirements.txt

RUN apt-get update -y \
	&& apt-get install -y \
        && pip install -r "/usr/src/docker/requirements.txt"\
	&& rm -rf /tmp/* \
	&& rm -rf /var/lib/apt/lists/* \
	&& apt-get clean 

WORKDIR /usr/src/app

COPY ./src .

CMD [ "/bin/bash" ]