FROM ubuntu:kinetic-20221101

RUN apt-get update && apt-get install -y \
    python3-pip

COPY ./docker/requirements-stgui.txt ./docker/requirements.txt

RUN pip install -r "./docker/requirements.txt"\
	&& rm -rf /tmp/* \
	&& rm -rf /var/lib/apt/lists/* \
	&& apt-get clean 

WORKDIR /usr/src/gui

COPY ./src/gui .

CMD [ "/bin/bash" ]